POST http://localhost:4004/odata/v4/vendor/Vendor
Content-Type: application/json

{
    "VendorNumber": "1230984567",
    "VendorFirstName": "Frank",
    "VendorLastName": "Thomas",
    "VendorEmail": "frank.thomas@example.com",
    "VendorPhoneNumber": "567-890-2345",
    "PONumber": "PO12365",
    "PurchasingGrp": "PG012",
    "InvoiceNumber": "INV12365",
    "PODescription": "Purchase order description for Frank",
    "Status": ""
}

